from __future__ import annotations

import json
from pathlib import Path

from anu_kernel import contracts, reality_contracts, ingestion_contracts, capability_contracts, sbbs_runtime_contracts, work_contracts

MODELS = {
    "anu.identity.v1": contracts.IdentityContract,
    "anu.semantic-definition.v1": contracts.SemanticDefinitionContract,
    "anu.role-assignment.v1": contracts.RoleAssignmentContract,
    "anu.competence-assertion.v1": contracts.CompetenceAssertionContract,
    "anu.authority-grant.v1": contracts.AuthorityGrantContract,
    "anu.delegation.v1": contracts.DelegationGrantContract,
    "anu.delegation-revocation.v1": contracts.DelegationRevocationContract,
    "anu.policy.v1": contracts.PolicyContract,
    "anu.policy-evaluation-request.v1": contracts.PolicyEvaluationRequest,
    "anu.policy-decision.v1": contracts.PolicyDecisionContract,
    "anu.provenance-record.v1": contracts.ProvenanceRecordContract,
    "anu.audit-event.v1": contracts.AuditEventContract,
    "anu.lifecycle-transition.v1": contracts.LifecycleTransitionContract,
    "anu.event-envelope.v1": contracts.KernelEventEnvelope,
    "anu.decision-record.v1": contracts.DecisionRecordContract,
    "anu.replay-request.v1": contracts.ReplayRequestContract,
    "anu.replay-result.v1": contracts.ReplayResultContract,
    "anu.authentication-context.v1": contracts.AuthenticationContext,
    "anu.governed-action-request.v1": contracts.GovernedActionRequest,
    "anu.enforcement-decision.v1": contracts.EnforcementDecisionContract,
    "anu.trust-credential.v1": contracts.TrustCredentialContract,
    "anu.signature-record.v1": contracts.SignatureRecordContract,
    "anu.signature-verification-result.v1": contracts.SignatureVerificationResult,
    "anu.agent-attestation.v1": contracts.AgentAttestationContract,
    "anu.attestation-verification-result.v1": contracts.AttestationVerificationResult,
    "anu.integrity-hash-request.v1": contracts.IntegrityHashRequest,
    "anu.integrity-hash-result.v1": contracts.IntegrityHashResult,
    "anu.source-registry.v1": reality_contracts.SourceRegistryContract,
    "anu.source-authority-mapping.v1": reality_contracts.SourceAuthorityMappingContract,
    "anu.data-contract.v1": reality_contracts.DataContractContract,
    "anu.data-envelope.v1": reality_contracts.DataEnvelopeContract,
    "anu.data-projection-request.v1": reality_contracts.DataProjectionRequest,
    "anu.data-projection-result.v1": reality_contracts.DataProjectionResult,
    "anu.knowledge-object.v1": reality_contracts.KnowledgeObjectContract,
    "anu.ingested-artifact.v1": reality_contracts.IngestedArtifactContract,
    "anu.memory-record.v1": reality_contracts.MemoryRecordContract,
    "anu.search-result-item.v1": reality_contracts.SearchResultItem,
    "anu.search-response.v1": reality_contracts.SearchResponse,
    "anu.provenance-graph-result.v1": reality_contracts.ProvenanceGraphResult,
    "anu.multimodal-artifact-ingest-request.v1": ingestion_contracts.MultimodalArtifactIngestRequest,
    "anu.multimodal-artifact-ingest-result.v1": ingestion_contracts.MultimodalArtifactIngestResult,
    "anu.artifact-integrity-result.v1": ingestion_contracts.ArtifactIntegrityResult,
    "anu.knowledge-materialization-request.v1": ingestion_contracts.KnowledgeMaterializationRequest,
    "anu.knowledge-materialization-result.v1": ingestion_contracts.KnowledgeMaterializationResult,
    "anu.retrieval-query.v1": ingestion_contracts.RetrievalQuery,
    "anu.retrieval-response.v1": ingestion_contracts.RetrievalResponse,
    "anu.capability-contract.v1": capability_contracts.CapabilityContract,
    "anu.smart-box-manifest.v1": capability_contracts.SmartBoxManifest,
    "anu.capability-discovery-query.v1": capability_contracts.CapabilityDiscoveryQuery,
    "anu.capability-discovery-response.v1": capability_contracts.CapabilityDiscoveryResponse,
    "anu.compatibility-context.v1": sbbs_runtime_contracts.CompatibilityContext,
    "anu.compatibility-check-request.v1": sbbs_runtime_contracts.CompatibilityCheckRequest,
    "anu.compatibility-result.v1": sbbs_runtime_contracts.CompatibilityResult,
    "anu.transform-definition.v1": sbbs_runtime_contracts.TransformDefinition,
    "anu.adapter-definition.v1": sbbs_runtime_contracts.AdapterDefinition,
    "anu.connection-plan-request.v1": sbbs_runtime_contracts.ConnectionPlanRequest,
    "anu.connection-plan.v1": sbbs_runtime_contracts.ConnectionPlan,
    "anu.smart-wire-execution-request.v1": sbbs_runtime_contracts.SmartWireExecutionRequest,
    "anu.smart-wire-execution-result.v1": sbbs_runtime_contracts.SmartWireExecutionResult,
    "anu.assembly-definition.v1": sbbs_runtime_contracts.AssemblyDefinition,
    "anu.assembly-execution-request.v1": sbbs_runtime_contracts.AssemblyExecutionRequest,
    "anu.assembly-execution-result.v1": sbbs_runtime_contracts.AssemblyExecutionResult,
    "anu.architecture-audit-report.v1": sbbs_runtime_contracts.ArchitectureAuditReport,
    "anu.write-box-proposal-request.v1": sbbs_runtime_contracts.WriteBoxProposalRequest,
    "anu.write-box-proposal-result.v1": sbbs_runtime_contracts.WriteBoxProposalResult,
    "anu.write-box-promotion-request.v1": sbbs_runtime_contracts.WriteBoxPromotionRequest,
    "anu.write-box-promotion-result.v1": sbbs_runtime_contracts.WriteBoxPromotionResult,
    "anu.work-contract.v1": work_contracts.WorkContract,
    "anu.governed-work-graph.v1": work_contracts.GovernedWorkGraph,
    "anu.execution-plan-request.v1": work_contracts.ExecutionPlanRequest,
    "anu.execution-plan.v1": work_contracts.ExecutionPlan,
    "anu.work-start-request.v1": work_contracts.WorkStartRequest,
    "anu.work-instance.v1": work_contracts.WorkInstanceView,
    "anu.work-task-request.v1": work_contracts.WorkTaskRequest,
    "anu.work-task-result.v1": work_contracts.WorkTaskResult,
    "anu.work-transition-request.v1": work_contracts.WorkTransitionRequest,
    "anu.work-transition-result.v1": work_contracts.WorkTransitionResult,
    "anu.handover-request.v1": work_contracts.HandoverRequest,
    "anu.handover-result.v1": work_contracts.HandoverResult,
    "anu.responsibility-trace-item.v1": work_contracts.ResponsibilityTraceItem,
    "anu.work-replay-result.v1": work_contracts.WorkReplayResult,
}

out = Path(__file__).resolve().parents[1] / "contracts" / "schemas"
out.mkdir(parents=True, exist_ok=True)
for name, model in MODELS.items():
    schema = model.model_json_schema(mode="validation")
    schema["$id"] = f"urn:anu:schema:{name}"
    (out / f"{name}.json").write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n")
print(f"exported {len(MODELS)} schemas to {out}")
